default_agent: restaurant_finder
is_agentcore_create_with_iac: true
agents:
  restaurant_finder:
    name: restaurant_finder
    entrypoint: agentcore
    deployment_type: container
    source_path: /
    aws:
      account: "339713078134"
      region: us-east-2
    bedrock_agentcore:
      # These values will be updated after CDK deployment
      agent_id: restaurantFinder_Agent
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:339713078134:runtime/restaurantFinder_Agent
      agent_endpoint_id: DEFAULT
      agent_session_id: null
    environment:
      ENABLE_BROWSER_SEARCH: "true"
      GUARDRAIL_ENABLED: "true"
    is_generated_by_agentcore_create: true
